# processos_app/urls.py (Updated)

from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='index'),
    path('cadastrar', views.cadastrar_processo, name='cadastrar_processo'),
    path('salvar', views.salvar_processo, name='salvar_processo'),
    path('listar', views.listar_processos, name='listar_processos'),
    path('processo/<int:process_id>/historico',
         views.ver_historico_processo, name='ver_historico_processo'),
    path('atualizar/<int:id>', views.atualizar_processo, name='atualizar_processo'),
    path('finalizados', views.listar_finalizados, name='listar_finalizados'),
    path('exportar_finalizados_excel', views.exportar_finalizados_excel,
         name='exportar_finalizados_excel'),
    path('get_process_by_number/<str:numero_processo>',
         views.get_process_by_number, name='get_process_by_number'),
    path('deletar/<int:id>', views.deletar_processo, name='deletar_processo'),
    path('processo/<int:process_id>/concluir_monitoramento/',
         views.concluir_monitoramento, name='concluir_monitoramento'),
    path('processo/<int:process_id>/marcar_saida/',
         views.marcar_saida_processo, name='marcar_saida_processo'),
    path('register/', views.register, name='register'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('manage_users/update_level/<int:user_id>/',
         views.update_user_level, name='update_user_level'),
    path('manage_users/delete/<int:user_id>/',
         views.delete_user, name='delete_user'),
    path('api/get_especies_by_genero/', views.get_especies_by_genero,
         name='get_especies_by_genero'),
    path('api/get_all_especies/', views.get_all_especies, name='get_all_especies'),
    path('analista/', views.area_analista, name='area_analista'),
    path('analista/processo/<int:process_id>/',
         views.analista_processo, name='analista_processo'),
    path('analista/processo/<int:process_id>/pendencia/',
         views.adicionar_pendencia, name='adicionar_pendencia'),
    path('analista/pendencia/<int:pendencia_id>/remover/',
         views.remover_pendencia, name='remover_pendencia'),
]
