# Generated by Django 5.2.3 on 2025-06-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=255, unique=True, verbose_name='Número de Processo')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Volume')),
                ('secretaria', models.CharField(max_length=255, verbose_name='Secretaria')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destino')),
                ('genero', models.CharField(max_length=255, verbose_name='Gênero')),
                ('especie', models.CharField(max_length=255, verbose_name='Espécie')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('contratada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contratada/Interessada')),
                ('recorrente', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='NÃO', max_length=3, verbose_name='Recorrente')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'BAIXA'), ('MÉDIA', 'MÉDIA'), ('ALTA', 'ALTA'), ('URGENTE', 'URGENTE')], max_length=50, verbose_name='Grau de Prioridade')),
                ('tecnico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Técnico Responsável Análise')),
                ('data_analise', models.DateField(blank=True, null=True, verbose_name='Data da Análise')),
                ('numero_despacho', models.CharField(blank=True, max_length=255, null=True, verbose_name='Controle do N° de Despacho')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('aviso_enviado', models.IntegerField(default=0, verbose_name='Aviso Enviado')),
            ],
            options={
                'db_table': 'processos',
            },
        ),
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor Antigo')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Novo Valor')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Mudança')),
                ('changed_by', models.CharField(default='Sistema', max_length=255, verbose_name='Alterado Por')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos_app.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Histórico do Processo',
                'verbose_name_plural': 'Histórico dos Processos',
                'db_table': 'process_history',
            },
        ),
    ]
