# Generated by Django 5.2.3 on 2025-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0002_alter_processhistory_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Volume'),
        ),
    ]
