# Generated by Django 5.2.3 on 2025-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0003_alter_processo_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'verbose_name_plural': 'Processos'},
        ),
        migrations.AddField(
            model_name='processo',
            name='prazo_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo em Dias'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='prioridade',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], default='NAO', max_length=50, verbose_name='Prioridade'),
        ),
    ]
