# Generated by Django 5.2.3 on 2025-07-08 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0004_alter_processo_options_processo_prazo_dias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='prazo_monitoramento',
            field=models.CharField(blank=True, choices=[('SEMESTRAL', 'Semestral'), ('QUADRIMESTRAL', 'Quadrimestral'), ('ANUAL', 'Anual'), ('TRIMESTRAL', 'Trimestral'), ('NAO_APLICAVEL', 'Não Aplicável')], max_length=20, null=True, verbose_name='Prazo de Monitoramento'),
        ),
        migrations.AddField(
            model_name='processo',
            name='proxima_data_monitoramento',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Data de Monitoramento'),
        ),
        migrations.AddField(
            model_name='processo',
            name='status_monitoramento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado'), ('NAO_APLICAVEL', 'Não Aplicável')], default='NAO_APLICAVEL', max_length=20, verbose_name='Status de Monitoramento'),
        ),
        migrations.CreateModel(
            name='MonitoramentoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramento_registros', to='processos_app.processo', verbose_name='Processo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Registro de Monitoramento',
                'verbose_name_plural': 'Registros de Monitoramento',
                'db_table': 'monitoramento_registros',
            },
        ),
    ]
