# Generated by Django 5.2.3 on 2025-07-09 14:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0005_processo_prazo_monitoramento_and_more'),
    ]

    operations = [
        # Remover a constraint UNIQUE diretamente no banco
        migrations.RunSQL(
            sql="ALTER TABLE processos DROP CONSTRAINT IF EXISTS processos_numero_processo_key;",
            reverse_sql="ALTER TABLE processos ADD CONSTRAINT processos_numero_processo_key UNIQUE (numero_processo);"
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(max_length=255, verbose_name='Número de Processo'),
        ),
    ]
