# Generated by Django 5.2.3 on 2025-07-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('0', 'Protocolo'), ('1', 'Analista 1 (Licitações e Contratos)'), ('2', 'Analista 2 (Liquidações)'), ('3', 'Usuário Geral (Todos)')], default='3', max_length=1),
        ),
    ]
