# Generated by Django 5.2.3 on 2025-07-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0008_alter_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='periodo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('PROSSEGUIMENTO_SEM_RESSALVA', 'Prosseguimento sem ressalva'), ('PROSSEGUIMENTO_COM_RESSALVA', 'Prosseguimento com ressalva'), ('NAO_PROSSEGUIMENTO', 'Não Prosseguimento'), ('DEVOLUCAO_PARA_SANEAMENTO', 'Devolução para saneamento')], default='PROSSEGUIMENTO_SEM_RESSALVA', max_length=50, verbose_name='Status do Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
