# Generated by Django 5.2.3 on 2025-07-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0009_processo_periodo_processo_status_processo_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='valor',
        ),
    ]
