# Generated by Django 5.2.3 on 2025-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0010_remove_processo_periodo_remove_processo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='periodo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='processo',
            name='status_analise',
            field=models.CharField(choices=[('PROSSEGUIMENTO_SEM_RESSALVA', 'Prosseguimento sem ressalva'), ('PROSSEGUIMENTO_COM_RESSALVA', 'Prosseguimento com ressalva'), ('NAO_PROSSEGUIMENTO', 'Não Prosseguimento'), ('DEVOLUCAO_PARA_SANEAMENTO', 'Devolução para saneamento'), ('NAO_APLICAVEL', 'Não Aplicável')], default='NAO_APLICAVEL', max_length=50, verbose_name='Status da Análise'),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor'),
        ),
    ]
