# Generated by Django 5.2.3 on 2025-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0011_processo_periodo_processo_status_analise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='volume',
            field=models.CharField(max_length=255, verbose_name='Volume'),
        ),
    ]
