# Generated by Django 5.2.5 on 2026-09-04 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0012_alter_processo_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='tem_pendencia',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NÃO')], default='NAO', max_length=3, verbose_name='Tem Pendência'),
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Pendência')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criada Por')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='processos_app.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
                'db_table': 'pendencias',
                'ordering': ['criada_em'],
            },
        ),
    ]
