# Generated by Django 5.2.5 on 2026-09-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0020_urgencia_recorrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaControleRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=255, verbose_name='Nº do processo')),
                ('volume', models.CharField(blank=True, max_length=255, verbose_name='Volume')),
                ('numero_relatorio', models.CharField(max_length=50, verbose_name='Nº do relatório')),
                ('data_relatorio', models.DateField(verbose_name='Data do relatório')),
                ('secretaria', models.CharField(blank=True, max_length=255, verbose_name='Secretaria')),
                ('contratada', models.CharField(blank=True, max_length=255, verbose_name='Contratada')),
                ('objeto', models.TextField(blank=True, verbose_name='Objeto')),
                ('valor', models.CharField(blank=True, max_length=255, verbose_name='Valor')),
                ('periodo', models.CharField(blank=True, max_length=255, verbose_name='Período')),
                ('destino', models.CharField(blank=True, max_length=255, verbose_name='Destino')),
                ('analista', models.CharField(blank=True, max_length=255, verbose_name='Analista')),
                ('status_analise', models.CharField(blank=True, max_length=50, verbose_name='Status da análise')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('grupo', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Grupo')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('processo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linha_relatorio', to='processos_app.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Linha de Controle de Relatório',
                'verbose_name_plural': 'Controle de Relatório',
                'db_table': 'controle_relatorio',
                'ordering': ['-data_relatorio', '-id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('grupo', 'numero_relatorio'),
                        name='uniq_controle_relatorio_grupo_numero',
                    ),
                ],
            },
        ),
    ]
