# Generated by Django 5.2.5 on 2026-10-01 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0024_devolvido_pela_gestao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linhacontrolerelatorio',
            options={'ordering': ['numero_relatorio', '-id'], 'verbose_name': 'Linha de Controle de Relatório', 'verbose_name_plural': 'Controle de Relatório'},
        ),
        migrations.AlterField(
            model_name='processo',
            name='situacao_tramite',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível para análise'), ('EM_ANALISE', 'Em análise'), ('ASSINATURA_DIRECIONADA', 'Direcionado para assinatura'), ('AGUARDANDO_ASSINATURA', 'Com o Controlador'), ('DISPONIVEL_RETIRADA', 'Disponível para retirada'), ('SAIDA_CONCLUIDA', 'Saída concluída')], db_index=True, default='DISPONIVEL', max_length=30, verbose_name='Situação da tramitação'),
        ),
        migrations.CreateModel(
            name='ReservaNumeroRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(db_index=True, max_length=50, verbose_name='Grupo')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('data', models.DateField(verbose_name='Data do relatório')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Destinado em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_relatorio', to=settings.AUTH_USER_MODEL, verbose_name='Destinado por')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_relatorio', to='processos_app.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Número de relatório destinado',
                'verbose_name_plural': 'Números de relatório destinados',
                'db_table': 'reservas_numero_relatorio',
                'ordering': ['numero', 'id'],
                'constraints': [models.UniqueConstraint(fields=('grupo', 'numero'), name='reserva_relatorio_unica')],
            },
        ),
    ]
