# Generated by Django 5.2.5 on 2026-10-01 16:58

from django.db import migrations, models


def preencher_sequencias(apps, schema_editor):
    Linha = apps.get_model('processos_app', 'LinhaControleRelatorio')
    Especie = apps.get_model('processos_app', 'EspecieProcesso')
    mapa = {
        'pagamento geral': 'LIQUIDACOES',
        'reanálise': 'LIQUIDACOES',
        'concessão adiantamento': 'ADIANTAMENTO',
        'p.c. adiantamento': 'ADIANTAMENTO',
        'concessão patrocínio': 'COTA_PATROCINIO',
        'p.c. patrocínio': 'COTA_PATROCINIO',
        'subvenção social - concessão': 'SUBVENCAO',
        'subvenção social - pagamento': 'SUBVENCAO',
        'subvenção social - prestação de contas': 'SUBVENCAO',
        'subvenção social - p.c. anual': 'SUBVENCAO',
        'subvenção social - renovação': 'SUBVENCAO',
        'concessão aux. aluguel social': 'ALUGUEL_SOCIAL',
        'concessão aux. bolsa atleta': 'BOLSA_ATLETA',
        'p.c. bolsa atleta': 'BOLSA_ATLETA',
        'concessão diária': 'DIARIA',
        'subvenção bloco carnaval': 'BLOCOS_CARNAVALESCOS',
        'p.c. subvenção bloco carnaval': 'BLOCOS_CARNAVALESCOS',
    }
    especies = {
        e.id: (e.nome or '').strip().casefold()
        for e in Especie.objects.all()
    }
    for linha in Linha.objects.filter(sequencia='').select_related('processo'):
        codigo = 'LIQUIDACOES'
        processo = linha.processo
        if processo is not None:
            nome = ''
            if processo.especie_fk_id:
                nome = especies.get(processo.especie_fk_id, '')
            if not nome:
                nome = (processo.especie or '').strip().casefold()
            codigo = mapa.get(nome, 'LIQUIDACOES')
        linha.sequencia = codigo
        linha.save(update_fields=['sequencia'])


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0025_reserva_numero_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhacontrolerelatorio',
            name='sequencia',
            field=models.CharField(
                blank=True, db_index=True, max_length=50,
                verbose_name='Sequência de numeração'),
        ),
        migrations.RunPython(preencher_sequencias, migrations.RunPython.noop),
    ]
