# Generated by Django 5.2.5 on 2026-10-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0026_linha_controle_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='observacao_protocolo',
            field=models.TextField(
                blank=True, default='',
                verbose_name='Observação do Protocolo'),
        ),
    ]
