# Generated by Django 5.2.5

from django.db import migrations


SECRETARIA_CGM = 'Controladoria Geral do Município'


def criar_secretaria_cgm(apps, schema_editor):
    Unidade = apps.get_model('processos_app', 'UnidadeAdministrativa')
    Unidade.objects.get_or_create(
        nome=SECRETARIA_CGM,
        defaults={
            'sigla': 'CGM',
            'ativo': True,
            'ordem': 5,
        },
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0027_observacao_protocolo'),
    ]

    operations = [
        migrations.RunPython(criar_secretaria_cgm, noop),
    ]
