# Generated by Django 5.2.5

from django.db import migrations, models


GRUPO_CONTABILIDADE = 'CONTABILIDADE'
ESPECIE_CONTABILIDADE = 'Contabilidade'


def criar_especie_contabilidade(apps, schema_editor):
    Especie = apps.get_model('processos_app', 'EspecieProcesso')
    Especie.objects.get_or_create(
        nome=ESPECIE_CONTABILIDADE,
        grupo=GRUPO_CONTABILIDADE,
        defaults={
            'ativo': True,
            'ordem': 10,
            'exige_contratada': False,
            'exige_valor': False,
            'gera_relatorio': False,
            'tipo_monitoramento': 'NENHUM',
        },
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0028_secretaria_cgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especieprocesso',
            name='grupo',
            field=models.CharField(
                choices=[
                    ('LICITACOES_E_CONTRATOS', 'Licitações e Contratos'),
                    ('LIQUIDACOES', 'Liquidações'),
                    ('CONTABILIDADE', 'Contabilidade'),
                ],
                db_index=True,
                max_length=30,
                verbose_name='Grupo',
            ),
        ),
        migrations.RunPython(criar_especie_contabilidade, noop),
    ]
