# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0029_especie_contabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='sem_relatorio',
            field=models.BooleanField(
                default=False,
                verbose_name='Despachado sem relatório',
            ),
        ),
        migrations.AddField(
            model_name='linhacontrolerelatorio',
            name='sem_relatorio',
            field=models.BooleanField(
                default=False,
                verbose_name='Despachado sem relatório',
            ),
        ),
        migrations.AlterField(
            model_name='linhacontrolerelatorio',
            name='numero_relatorio',
            field=models.CharField(
                blank=True,
                default='',
                max_length=50,
                verbose_name='Nº do relatório',
            ),
        ),
    ]
