# Generated by Django 5.2.5

from django.db import migrations, models


# Espécie → sequência (espelha relatorios.SEQUENCIAS no momento da migration).
MAPA_ESPECIE_SEQUENCIA = {
    'pagamento geral': 'LIQUIDACOES',
    'reanálise': 'LIQUIDACOES',
    'reanalise': 'LIQUIDACOES',
    'concessão adiantamento': 'ADIANTAMENTO',
    'concessao adiantamento': 'ADIANTAMENTO',
    'p.c. adiantamento': 'ADIANTAMENTO',
    'concessão patrocínio': 'COTA_PATROCINIO',
    'concessao patrocinio': 'COTA_PATROCINIO',
    'p.c. patrocínio': 'COTA_PATROCINIO',
    'p.c. patrocinio': 'COTA_PATROCINIO',
    'subvenção social - concessão': 'SUBVENCAO',
    'subvencao social - concessao': 'SUBVENCAO',
    'subvenção social - pagamento': 'SUBVENCAO',
    'subvencao social - pagamento': 'SUBVENCAO',
    'subvenção social - prestação de contas': 'SUBVENCAO',
    'subvencao social - prestacao de contas': 'SUBVENCAO',
    'subvenção social - p.c. anual': 'SUBVENCAO',
    'subvencao social - p.c. anual': 'SUBVENCAO',
    'subvenção social - renovação': 'SUBVENCAO',
    'subvencao social - renovacao': 'SUBVENCAO',
    'concessão aux. aluguel social': 'ALUGUEL_SOCIAL',
    'concessao aux. aluguel social': 'ALUGUEL_SOCIAL',
    'concessão aux. bolsa atleta': 'BOLSA_ATLETA',
    'concessao aux. bolsa atleta': 'BOLSA_ATLETA',
    'p.c. bolsa atleta': 'BOLSA_ATLETA',
    'concessão diária': 'DIARIA',
    'concessao diaria': 'DIARIA',
    'subvenção bloco carnaval': 'BLOCOS_CARNAVALESCOS',
    'subvencao bloco carnaval': 'BLOCOS_CARNAVALESCOS',
    'p.c. subvenção bloco carnaval': 'BLOCOS_CARNAVALESCOS',
    'p.c. subvenca bloco carnaval': 'BLOCOS_CARNAVALESCOS',
    'p.c. subvenção bloco carnaval': 'BLOCOS_CARNAVALESCOS',
}


def popular_sequencia(apps, schema_editor):
    Especie = apps.get_model('processos_app', 'EspecieProcesso')
    for especie in Especie.objects.all():
        chave = (especie.nome or '').strip().casefold()
        codigo = MAPA_ESPECIE_SEQUENCIA.get(chave, '')
        if codigo and especie.grupo == 'LIQUIDACOES':
            especie.sequencia_numeracao = codigo
            especie.save(update_fields=['sequencia_numeracao'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processos_app', '0031_sequencia_relatorio_ajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='especieprocesso',
            name='sequencia_numeracao',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                max_length=50,
                verbose_name='Grupo do relatório',
            ),
        ),
        migrations.RunPython(popular_sequencia, noop),
    ]
